import React from 'react'
import '@/app/(screen)/globals.css'
// import { Toaster } from "../../components/ui/toaster"
import { Metadata } from 'next';
import { CartProvider } from '@/components/contextApi/AddToaCart';
export const metadata: Metadata = {
    title: "Ecomart",
    description: "Generated by Ammar shaikh",
};
const AuthLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html>
            <body suppressHydrationWarning={true}>
                <CartProvider>
                    {children}
                </CartProvider>
                {/* <Toaster /> */}
            </body>
        </html>
    )
}

export default AuthLayout